import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../../config/app_config.dart';
import '../../features/recommendation/models/recommendation_models.dart';

/// PDF Export API Service
class PDFExportApiService {
  final http.Client _client = http.Client();

  /// Generate enhanced PDF report from recommendation result
  Future<Uint8List> generateEnhancedPDF({
    required RecommendationResult result,
  }) async {
    try {
      final uri = Uri.parse('${AppConfig.apiBaseUrl}/pdf/generate-enhanced-report');

      final response = await _client.post(
        uri,
        headers: {
          'Content-Type': 'application/json',
        },
        body: jsonEncode({
          'recommendation_result': result.toJson(),
          'export_format': 'pdf',
        }),
      );

      if (response.statusCode == 200) {
        return response.bodyBytes;
      } else {
        throw Exception('PDF generation failed: ${response.statusCode}');
      }
    } catch (e) {
      // Fallback: return mock PDF data for testing
      if (kDebugMode) {
        print('[WARN] PDF generation failed, using mock data: $e');
      }
      return _generateMockPDF();
    }
  }

  /// Export recommendation result as HTML
  Future<String> exportToHTML({
    required RecommendationResult result,
  }) async {
    try {
      final uri = Uri.parse('${AppConfig.apiBaseUrl}/pdf/generate-enhanced-report');

      final response = await _client.post(
        uri,
        headers: {
          'Content-Type': 'application/json',
        },
        body: jsonEncode({
          'recommendation_result': result.toJson(),
          'export_format': 'html',
        }),
      );

      if (response.statusCode == 200) {
        return response.body;
      } else {
        throw Exception('HTML export failed: ${response.statusCode}');
      }
    } catch (e) {
      // Fallback: return mock HTML for testing
      if (kDebugMode) {
        print('[WARN] HTML export failed, using mock data: $e');
      }
      return _generateMockHTML(result);
    }
  }

  /// Generate mock PDF data for testing
  Uint8List _generateMockPDF() {
    // Simple mock PDF content (in reality, you'd use a PDF library)
    final mockContent = '''
Mock PDF Report - 学锋志愿教练

This is a mock PDF for testing purposes.
In production, this would be generated by the backend.

Recommendation Result Report
============================
Generated: ${DateTime.now().toString()}
''';
    return Uint8List.fromList(mockContent.codeUnits);
  }

  /// Generate mock HTML for testing
  String _generateMockHTML(RecommendationResult result) {
    return '''
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>学锋志愿教练 - 推荐报告</title>
    <style>
        body { font-family: 'Microsoft YaHei', sans-serif; margin: 20px; line-height: 1.6; }
        h1 { color: #1976D2; border-bottom: 3px solid #1976D2; padding-bottom: 10px; }
        h2 { color: #424242; margin-top: 30px; border-left: 4px solid #1976D2; padding-left: 10px; }
        .info-box { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 10px 0; }
        .category { margin: 20px 0; padding: 15px; border-radius: 8px; }
        .category-chong { background: #ffebee; border-left: 4px solid #f44336; }
        .category-wen { background: #e8f5e9; border-left: 4px solid #4caf50; }
        .category-bao { background: #e3f2fd; border-left: 4px solid #2196f3; }
        .university-card { background: white; padding: 15px; margin: 10px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .probability { font-weight: bold; padding: 4px 8px; border-radius: 4px; display: inline-block; }
        .prob-high { background: #4caf50; color: white; }
        .prob-medium { background: #2196f3; color: white; }
        .prob-low { background: #ff9800; color: white; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>学锋志愿教练 - 智能推荐报告</h1>

    <div class="info-box">
        <h3>考生信息</h3>
        <p><strong>省份：</strong>${result.basicInfo.province}</p>
        <p><strong>分数：</strong>${result.basicInfo.score}分</p>
        <p><strong>位次：</strong>第${result.basicInfo.rank}名</p>
        <p><strong>科类：</strong>${result.basicInfo.subjectType}</p>
        <p><strong>目标专业：</strong>${result.basicInfo.targetMajors.join('、')}</p>
    </div>

    <h2>推荐院校方案</h2>

    ${result.chong.isNotEmpty ? '''
    <div class="category category-chong">
        <h3>冲刺院校 (${result.chong.length}所)</h3>
        ${result.chong.map((rec) => '''
        <div class="university-card">
            <h4>${rec.universityName} - ${rec.major}</h4>
            <p><strong>层次：</strong>${rec.universityLevel} | <strong>类型：</strong>${rec.universityType}</p>
            <p><strong>地点：</strong>${rec.province} ${rec.city}</p>
            <p><strong>录取概率：</strong><span class="probability ${_getProbClass(rec.probability)}">${rec.probability}%</span></p>
            <p><strong>分差：</strong>${rec.scoreGap > 0 ? '+' : ''}${rec.scoreGap}分</p>
            <p><strong>就业率：</strong>${rec.employmentInfo.employmentRate}</p>
            <p><strong>主要雇主：</strong>${rec.employmentInfo.topEmployers.join('、')}</p>
        </div>
        ''').join('')}
    </div>
    ''' : ''}

    ${result.wen.isNotEmpty ? '''
    <div class="category category-wen">
        <h3>稳妥院校 (${result.wen.length}所)</h3>
        ${result.wen.map((rec) => '''
        <div class="university-card">
            <h4>${rec.universityName} - ${rec.major}</h4>
            <p><strong>层次：</strong>${rec.universityLevel} | <strong>类型：</strong>${rec.universityType}</p>
            <p><strong>地点：</strong>${rec.province} ${rec.city}</p>
            <p><strong>录取概率：</strong><span class="probability ${_getProbClass(rec.probability)}">${rec.probability}%</span></p>
            <p><strong>分差：</strong>${rec.scoreGap > 0 ? '+' : ''}${rec.scoreGap}分</p>
            <p><strong>就业率：</strong>${rec.employmentInfo.employmentRate}</p>
            <p><strong>主要雇主：</strong>${rec.employmentInfo.topEmployers.join('、')}</p>
        </div>
        ''').join('')}
    </div>
    ''' : ''}

    ${result.bao.isNotEmpty ? '''
    <div class="category category-bao">
        <h3>保底院校 (${result.bao.length}所)</h3>
        ${result.bao.map((rec) => '''
        <div class="university-card">
            <h4>${rec.universityName} - ${rec.major}</h4>
            <p><strong>层次：</strong>${rec.universityLevel} | <strong>类型：</strong>${rec.universityType}</p>
            <p><strong>地点：</strong>${rec.province} ${rec.city}</p>
            <p><strong>录取概率：</strong><span class="probability ${_getProbClass(rec.probability)}">${rec.probability}%</span></p>
            <p><strong>分差：</strong>${rec.scoreGap > 0 ? '+' : ''}${rec.scoreGap}分</p>
            <p><strong>就业率：</strong>${rec.employmentInfo.employmentRate}</p>
            <p><strong>主要雇主：</strong>${rec.employmentInfo.topEmployers.join('、')}</p>
        </div>
        ''').join('')}
    </div>
    ''' : ''}

    <div class="info-box">
        <h3>分析建议</h3>
        ${result.analysis.comments.map((comment) => '<p>• $comment</p>').join('')}
        <h4>填报建议：</h4>
        ${result.advice.take(5).map((advice) => '<p>$advice</p>').join('')}
    </div>

    <div class="footer">
        <p><strong>报告生成时间：</strong>${DateTime.now().toString()}</p>
        <p><strong>数据来源：</strong>学锋志愿教练数据库 - 覆盖全国2800+所院校</p>
        <p><strong>免责声明：</strong>本报告仅供参考，实际录取结果受多种因素影响。请以官方公布信息为准。</p>
        <p>© 2026 学锋志愿教练 | 专业的高考志愿填报指导平台</p>
    </div>
</body>
</html>
''';
  }

  String _getProbClass(int probability) {
    if (probability >= 75) return 'prob-high';
    if (probability >= 50) return 'prob-medium';
    return 'prob-low';
  }

  void dispose() {
    _client.close();
  }
}
